# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_new.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../.designer/images for Qt5/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1051, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1041, 561))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(40, 0))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(710, 210, 281, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.line = QtWidgets.QFrame(self.tab_4)
        self.line.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(710, 70, 281, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(710, 40, 100, 28))
        self.label_31.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_31.setObjectName("label_31")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_19.setGeometry(QtCore.QRect(730, 160, 240, 28))
        self.pushButton_19.setObjectName("pushButton_19")
        self.listWidget = QtWidgets.QListWidget(self.tab_4)
        self.listWidget.setGeometry(QtCore.QRect(710, 110, 281, 41))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.listWidget.setFont(font)
        self.listWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.listWidget.setMouseTracking(True)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget.setLineWidth(1)
        self.listWidget.setMidLineWidth(0)
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setItemAlignment(QtCore.Qt.AlignCenter)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(710, 50, 281, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_7.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.line_2 = QtWidgets.QFrame(self.tab_5)
        self.line_2.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.line_3 = QtWidgets.QFrame(self.tab_6)
        self.line_3.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.tab_6)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_13.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_13.addWidget(self.pushButton_6)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_6)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(710, 50, 281, 101))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_13.setMinimumSize(QtCore.QSize(25, 0))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_10.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_10.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_10.addWidget(self.lineEdit_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_11.addWidget(self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_11.addWidget(self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_11.addWidget(self.lineEdit_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_6)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_16 = QtWidgets.QLabel(self.tab_7)
        self.label_16.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.tab_7)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_15.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_15.addWidget(self.pushButton_8)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(710, 50, 281, 231))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 80, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_9.setMinimumSize(QtCore.QSize(40, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setMinimumSize(QtCore.QSize(40, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, 80, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_19.setMinimumSize(QtCore.QSize(40, 0))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_20.setMinimumSize(QtCore.QSize(40, 0))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.line_4 = QtWidgets.QFrame(self.tab_7)
        self.line_4.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.tab_7)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 641, 511))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_8)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_12.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_17 = QtWidgets.QLabel(self.tab_8)
        self.label_17.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.tab_8)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_17.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_17.addWidget(self.pushButton_10)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_8)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(710, 50, 281, 111))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line_5 = QtWidgets.QFrame(self.tab_8)
        self.line_5.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.tab_8)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_18 = QtWidgets.QLabel(self.tab_9)
        self.label_18.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.tab_9)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_19.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_19.addWidget(self.pushButton_12)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_9)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(710, 50, 281, 41))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_6.addWidget(self.checkBox_2)
        self.line_6 = QtWidgets.QFrame(self.tab_9)
        self.line_6.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.tab_9)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 1041, 561))
        self.tabWidget_3.setMinimumSize(QtCore.QSize(40, 0))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_16)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(710, 56, 281, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_7 = QtWidgets.QFrame(self.tab_16)
        self.line_7.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_25 = QtWidgets.QLabel(self.tab_16)
        self.label_25.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.tab_16)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_16)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_13 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_23.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_23.addWidget(self.pushButton_14)
        self.tabWidget_3.addTab(self.tab_16, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.tab_10)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.pushButton_17 = QtWidgets.QPushButton(self.horizontalLayoutWidget_18)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_27.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.horizontalLayoutWidget_18)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_27.addWidget(self.pushButton_18)
        self.line_9 = QtWidgets.QFrame(self.tab_10)
        self.line_9.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.tab_10)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_29 = QtWidgets.QLabel(self.tab_10)
        self.label_29.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.tab_10)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(710, 50, 281, 101))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_12.addWidget(self.label_27)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_28.setMinimumSize(QtCore.QSize(25, 0))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_29.addWidget(self.label_28)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_29.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_29.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_29.addWidget(self.lineEdit_17)
        self.verticalLayout_13.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_30.addWidget(self.label_30)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_30.addWidget(self.lineEdit_18)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_30.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_30.addWidget(self.lineEdit_20)
        self.verticalLayout_13.addLayout(self.horizontalLayout_30)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_11)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButton_15 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_24.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_24.addWidget(self.pushButton_16)
        self.line_8 = QtWidgets.QFrame(self.tab_11)
        self.line_8.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.tab_11)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_26 = QtWidgets.QLabel(self.tab_11)
        self.label_26.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_11)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(710, 56, 281, 91))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 1041, 561))
        self.tabWidget_4.setMinimumSize(QtCore.QSize(40, 0))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.line_10 = QtWidgets.QFrame(self.tab_17)
        self.line_10.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_32 = QtWidgets.QLabel(self.tab_17)
        self.label_32.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(self.tab_17)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayoutWidget_21 = QtWidgets.QWidget(self.tab_17)
        self.horizontalLayoutWidget_21.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_21.setObjectName("horizontalLayoutWidget_21")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_21)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pushButton_20 = QtWidgets.QPushButton(self.horizontalLayoutWidget_21)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_32.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.horizontalLayoutWidget_21)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_32.addWidget(self.pushButton_21)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget_2.setGeometry(QtCore.QRect(710, 60, 322, 221))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 60, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_32.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_5.addWidget(self.lineEdit_32, 3, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_45.setMinimumSize(QtCore.QSize(40, 0))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 5, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 6, 0, 1, 2)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_46.setMinimumSize(QtCore.QSize(40, 0))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 7, 0, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_33.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_5.addWidget(self.lineEdit_33, 7, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_47.setMinimumSize(QtCore.QSize(40, 0))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 3, 0, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_34.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_5.addWidget(self.lineEdit_34, 5, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 4, 0, 1, 2)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 2, 0, 1, 2)
        self.tabWidget_4.addTab(self.tab_17, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.horizontalLayoutWidget_22 = QtWidgets.QWidget(self.tab_12)
        self.horizontalLayoutWidget_22.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_22.setObjectName("horizontalLayoutWidget_22")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_22)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pushButton_22 = QtWidgets.QPushButton(self.horizontalLayoutWidget_22)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_33.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.horizontalLayoutWidget_22)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_33.addWidget(self.pushButton_23)
        self.line_11 = QtWidgets.QFrame(self.tab_12)
        self.line_11.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayoutWidget_23 = QtWidgets.QWidget(self.tab_12)
        self.horizontalLayoutWidget_23.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_23.setObjectName("horizontalLayoutWidget_23")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_23)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_33 = QtWidgets.QLabel(self.tab_12)
        self.label_33.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.layoutWidget = QtWidgets.QWidget(self.tab_12)
        self.layoutWidget.setGeometry(QtCore.QRect(709, 60, 271, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 60, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.horizontalLayoutWidget_24 = QtWidgets.QWidget(self.tab_13)
        self.horizontalLayoutWidget_24.setGeometry(QtCore.QRect(710, 490, 279, 30))
        self.horizontalLayoutWidget_24.setObjectName("horizontalLayoutWidget_24")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_24)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.pushButton_24 = QtWidgets.QPushButton(self.horizontalLayoutWidget_24)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_37.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.horizontalLayoutWidget_24)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_37.addWidget(self.pushButton_25)
        self.line_12 = QtWidgets.QFrame(self.tab_13)
        self.line_12.setGeometry(QtCore.QRect(660, 0, 16, 530))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayoutWidget_25 = QtWidgets.QWidget(self.tab_13)
        self.horizontalLayoutWidget_25.setGeometry(QtCore.QRect(10, 10, 640, 510))
        self.horizontalLayoutWidget_25.setObjectName("horizontalLayoutWidget_25")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_25)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_39 = QtWidgets.QLabel(self.tab_13)
        self.label_39.setGeometry(QtCore.QRect(710, 10, 279, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.tab_13)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(710, 56, 281, 91))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(3)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget_4.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Детектор резисторов"))
        self.label.setText(_translate("MainWindow", "*DELTA = (длина + ширина) / 2 * погрешность"))
        self.label_3.setText(_translate("MainWindow", "погрешность = "))
        self.lineEdit.setText(_translate("MainWindow", "0.05"))
        self.checkBox.setText(_translate("MainWindow", "Фильтрация входного изображения"))
        self.pushButton.setText(_translate("MainWindow", "Применить"))
        self.pushButton_2.setText(_translate("MainWindow", "Сбросить"))
        self.label_2.setText(_translate("MainWindow", "Настройки:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Изображение"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Камера"))
        self.label_31.setText(_translate("MainWindow", "Источник:"))
        self.pushButton_19.setText(_translate("MainWindow", "Выберите путь до изображения..."))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Здесь будет путь до изображения"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Исходник"))
        self.label_5.setText(_translate("MainWindow", "H"))
        self.label_6.setText(_translate("MainWindow", "S"))
        self.label_7.setText(_translate("MainWindow", "V"))
        self.pushButton_3.setText(_translate("MainWindow", "Применить"))
        self.pushButton_4.setText(_translate("MainWindow", "Сбросить"))
        self.label_4.setText(_translate("MainWindow", "Настройки:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "HSV"))
        self.label_15.setText(_translate("MainWindow", "Настройки:"))
        self.pushButton_5.setText(_translate("MainWindow", "Применить"))
        self.pushButton_6.setText(_translate("MainWindow", "Сбросить"))
        self.label_10.setText(_translate("MainWindow", "H"))
        self.label_11.setText(_translate("MainWindow", "S"))
        self.label_12.setText(_translate("MainWindow", "V"))
        self.label_13.setText(_translate("MainWindow", "min"))
        self.label_14.setText(_translate("MainWindow", "max"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Закрашивание"))
        self.label_16.setText(_translate("MainWindow", "Настройки:"))
        self.pushButton_7.setText(_translate("MainWindow", "Применить"))
        self.pushButton_8.setText(_translate("MainWindow", "Сбросить"))
        self.label_22.setText(_translate("MainWindow", "Заполнение"))
        self.label_9.setText(_translate("MainWindow", "Ky"))
        self.label_8.setText(_translate("MainWindow", "Kx"))
        self.label_21.setText(_translate("MainWindow", "Устранение выбросов"))
        self.label_19.setText(_translate("MainWindow", "Ky"))
        self.label_20.setText(_translate("MainWindow", "Kx"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Пороговая обработка"))
        self.label_17.setText(_translate("MainWindow", "Настройки:"))
        self.pushButton_9.setText(_translate("MainWindow", "Применить"))
        self.pushButton_10.setText(_translate("MainWindow", "Сбросить"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Контурирование"))
        self.label_18.setText(_translate("MainWindow", "Настройки:"))
        self.pushButton_11.setText(_translate("MainWindow", "Применить"))
        self.pushButton_12.setText(_translate("MainWindow", "Сбросить"))
        self.checkBox_2.setText(_translate("MainWindow", "Поворот схемы до горизонтали"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Результат"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Обнаружение схемы"))
        self.label_25.setText(_translate("MainWindow", "Настройки:"))
        self.pushButton_13.setText(_translate("MainWindow", "Применить"))
        self.pushButton_14.setText(_translate("MainWindow", "Сбросить"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_16), _translate("MainWindow", "Выбор опорной точки"))
        self.pushButton_17.setText(_translate("MainWindow", "Применить"))
        self.pushButton_18.setText(_translate("MainWindow", "Сбросить"))
        self.label_29.setText(_translate("MainWindow", "Настройки:"))
        self.label_23.setText(_translate("MainWindow", "H"))
        self.label_24.setText(_translate("MainWindow", "S"))
        self.label_27.setText(_translate("MainWindow", "V"))
        self.label_28.setText(_translate("MainWindow", "min"))
        self.label_30.setText(_translate("MainWindow", "max"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Выделение резисторов"))
        self.pushButton_15.setText(_translate("MainWindow", "Применить"))
        self.pushButton_16.setText(_translate("MainWindow", "Сбросить"))
        self.label_26.setText(_translate("MainWindow", "Настройки:"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MainWindow", "Результат"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Обнаружение резисторов"))
        self.label_32.setText(_translate("MainWindow", "Настройки:"))
        self.pushButton_20.setText(_translate("MainWindow", "Применить"))
        self.pushButton_21.setText(_translate("MainWindow", "Сбросить"))
        self.label_45.setText(_translate("MainWindow", "k_s"))
        self.label_38.setText(_translate("MainWindow", "Коэффициент влияния V (яркость)"))
        self.label_46.setText(_translate("MainWindow", "k_v"))
        self.label_47.setText(_translate("MainWindow", "k_h"))
        self.label_36.setText(_translate("MainWindow", "Коэффициент влияния S (насыщенность)"))
        self.label_48.setText(_translate("MainWindow", "Коэффициент влияния H (оттенок)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_17), _translate("MainWindow", "Обучение модели"))
        self.pushButton_22.setText(_translate("MainWindow", "Применить"))
        self.pushButton_23.setText(_translate("MainWindow", "Сбросить"))
        self.label_33.setText(_translate("MainWindow", "Настройки:"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "Обнаружение цветовых полосок"))
        self.pushButton_24.setText(_translate("MainWindow", "Применить"))
        self.pushButton_25.setText(_translate("MainWindow", "Сбросить"))
        self.label_39.setText(_translate("MainWindow", "Настройки:"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Результат"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Проверка резисторов"))
        self.action_2.setText(_translate("MainWindow", "Гы"))
